version: '2.1'
services:
    server1:
        cap_add:
            - NET_ADMIN
        build: bird.server
        volumes:
            - ~/gandi/devops/ecmp-lab/bird.server/server1:/etc/bird.d/
        networks:
            ecmp:
                ipv4_address: 192.168.123.2
                aliases:
                    - server1
        stop_signal: SIGKILL
        stdin_open: true
        tty: true
    server2:
        cap_add:
            - NET_ADMIN
        build: bird.server
        volumes:
            - ~/gandi/devops/ecmp-lab/bird.server/server1:/etc/bird.d/
        networks:
            ecmp:
                ipv4_address: 192.168.123.3
                aliases:
                    - server2
        stop_signal: SIGKILL
        stdin_open: true
        tty: true
    router1:
        cap_add:
            - NET_ADMIN
        build: bird.router
        volumes:
            - ~/gandi/devops/ecmp-lab/bird.router/router1:/etc/bird.d/
        networks:
            ecmp:
                ipv4_address: 192.168.123.4
                aliases:
                    - router1
            public:
                ipv4_address: 192.168.122.4
        stop_signal: SIGKILL
        stdin_open: true
        tty: true
        sysctls:
            - net.ipv4.ip_forward=1
    client1:
        cap_add:
            - NET_ADMIN
        build: bird.client
        volumes:
            - ~/gandi/devops/ecmp-lab/bird.client/client1:/etc/bird.d/
        networks:
            public:
                ipv4_address: 192.168.122.100
        stop_signal: SIGKILL
        stdin_open: true
        tty: true
    client2:
        cap_add:
            - NET_ADMIN
        build: bird.client
        volumes:
            - ~/gandi/devops/ecmp-lab/bird.client/client1:/etc/bird.d/
        networks:
            public:
                ipv4_address: 192.168.122.101
        stop_signal: SIGKILL
        stdin_open: true
    client3:
        cap_add:
            - NET_ADMIN
        build: bird.client
        volumes:
            - ~/gandi/devops/ecmp-lab/bird.client/client1:/etc/bird.d/
        networks:
            public:
                ipv4_address: 192.168.122.102
        stop_signal: SIGKILL
        stdin_open: true
    client4:
        cap_add:
            - NET_ADMIN
        build: bird.client
        volumes:
            - ~/gandi/devops/ecmp-lab/bird.client/client1:/etc/bird.d/
        networks:
            public:
                ipv4_address: 192.168.122.103
        stop_signal: SIGKILL
        stdin_open: true

volumes:
    bird.router:
        external: true
    bird.client:
        external: true
    bird.server:
        external: true
networks:
    ecmp:
        driver: bridge
        enable_ipv6: false
        internal: false
        ipam:
            driver: default
            config:
                - subnet: 192.168.123.0/24
    public:
        driver: bridge
        enable_ipv6: false
        internal: false
        ipam:
            driver: default
            config:
                - subnet: 192.168.122.0/24
